import { imageSize } from "image-size"
import fs from "node:fs/promises"
import path from "node:path"
import { getOwnPackageName } from "../shared/getOwnPackageName.js"
import { walkFiles } from "../shared/walkFiles.js"
import type { ImageType } from "./AssetListTypes.js"
import { formatGeneratedCodeFile } from "./formatGeneratedCodeFile.js"
import { getAssetKey } from "./getAssetKey.js"
import { loadExistingAssetList } from "./loadExistingAssetList.js"
import { sortAssetMap } from "./sortAssetMap.js"

const IMAGE_EXTENSIONS = new Set([".jpg", ".jpeg", ".png", ".gif", ".webp", ".avif", ".tiff", ".svg"])

export async function generateImageList(
  imageDirectory: string,
  outputPath: string,
  imageTypeImportPath?: string,
): Promise<void> {
  const resolvedImageTypeImportPath = imageTypeImportPath ?? (await getOwnPackageName(import.meta.url))
  const existingImages = await loadExistingAssetList<ImageType>(outputPath, "imageList")
  const imageMap = await processImageFiles(imageDirectory, existingImages)
  const sorted = sortAssetMap(imageMap)

  await fs.mkdir(path.dirname(outputPath), { recursive: true })
  await Bun.write(outputPath, createGeneratedImageListContent(sorted, resolvedImageTypeImportPath))
  await formatGeneratedCodeFile(outputPath)
  console.log(`Generated ${Object.keys(sorted).length} images to ${outputPath}`)
}

async function processImageFiles(
  directory: string,
  existingImages: Record<string, ImageType>,
): Promise<Record<string, ImageType>> {
  const imageMap: Record<string, ImageType> = {}

  for (const filePath of await walkFiles(directory)) {
    const extension = path.extname(filePath).toLowerCase()
    if (!IMAGE_EXTENSIONS.has(extension)) {
      continue
    }

    try {
      const buffer = await fs.readFile(filePath)
      const dimensions = imageSize(buffer)
      if (!dimensions.width || !dimensions.height) {
        continue
      }

      const relativePath = path.relative(directory, filePath)
      const key = normalizeGeneratedImageKey(getAssetKey(filePath))
      const fileName = path.basename(filePath, extension)

      imageMap[key] = {
        path: relativePath,
        width: dimensions.width,
        height: dimensions.height,
        alt: existingImages[key]?.alt || formatGeneratedImageAlt(fileName),
        mimeType: getImageMimeType(extension),
      }
    } catch (error) {
      console.error(`Error processing ${filePath}:`, error)
    }
  }
  return imageMap
}

function normalizeGeneratedImageKey(key: string): string {
  return key.replace(/_[0-9a-f]{8}$/i, "")
}

function formatGeneratedImageAlt(fileName: string): string {
  return normalizeGeneratedImageKey(fileName).replace(/[-_]/g, " ")
}

function createGeneratedImageListContent(imageMap: Record<string, ImageType>, imageTypeImportPath: string): string {
  return `import type { ImageType } from "${imageTypeImportPath}"

// Auto-generated, manual changes will be lost, generated by optimizeAssets from @adaptive-ds/assets-optimizer
export const imageList = ${JSON.stringify(imageMap, null, 2)} as const satisfies Record<string, ImageType>
`
}

function getImageMimeType(extension: string): string {
  switch (extension) {
    case ".jpg":
    case ".jpeg":
      return "image/jpeg"
    case ".png":
      return "image/png"
    case ".gif":
      return "image/gif"
    case ".webp":
      return "image/webp"
    case ".avif":
      return "image/avif"
    case ".tiff":
      return "image/tiff"
    case ".svg":
      return "image/svg+xml"
    default:
      return "application/octet-stream"
  }
}
