import fs from "node:fs/promises"
import path from "node:path"
import { getOwnPackageName } from "../shared/getOwnPackageName.js"
import { isMissingDirError } from "../shared/isMissingDirError.js"
import type { Logger } from "../shared/logger.js"
import { walkFiles } from "../shared/walkFiles.js"
import { supportedFontOutputExtensions } from "../font/supportedFontExtensions.js"
import type { FontType } from "./AssetListTypes.js"
import { formatGeneratedCodeFile } from "./formatGeneratedCodeFile.js"
import { getAssetKey } from "./getAssetKey.js"
import { loadExistingAssetList } from "./loadExistingAssetList.js"
import { sortAssetMap } from "./sortAssetMap.js"
import { parseFontFilename } from "../font/parseFontFilename.js"

export async function generateFontList(
  fontsDirectory: string,
  outputPath: string,
  fontTypeImportPath?: string,
  logger?: Logger,
): Promise<void> {
  const resolvedFontTypeImportPath = fontTypeImportPath ?? (await getOwnPackageName(import.meta.url))
  const existingFonts = await loadExistingAssetList<FontType>(outputPath, "fontList")
  const fontMap = sortAssetMap(await processFontFiles(fontsDirectory, existingFonts))

  await fs.mkdir(path.dirname(outputPath), { recursive: true })
  await Bun.write(outputPath, createGeneratedFontListContent(fontMap, resolvedFontTypeImportPath))
  await formatGeneratedCodeFile(outputPath, logger)
  logger?.files(`generated font list: ${outputPath}`)
  logger?.summary(`Generated ${Object.keys(fontMap).length} fonts to ${outputPath}`)
}

async function processFontFiles(
  directory: string,
  existingFonts: Record<string, FontType>,
): Promise<Record<string, FontType>> {
  const fontMap: Record<string, FontType> = {}

  let filePaths: string[]
  try {
    filePaths = await walkFiles(directory)
  } catch (error) {
    if (isMissingDirError(error)) {
      return fontMap
    }

    throw error
  }

  for (const filePath of filePaths) {
    const extension = path.extname(filePath).toLowerCase()
    if (!supportedFontOutputExtensions.has(extension)) {
      continue
    }

    const relativePath = path.relative(directory, filePath)
    const key = getAssetKey(filePath)
    const fontMeta = parseFontFilename(filePath)

    fontMap[key] = {
      path: relativePath,
      fontFamily: fontMeta.fontFamily,
      fontStyle: fontMeta.fontStyle,
      fontWeight: fontMeta.fontWeight,
      mimeType: "font/woff2",
    }
  }
  return fontMap
}

function createGeneratedFontListContent(fontMap: Record<string, FontType>, fontTypeImportPath: string): string {
  return `import type { FontType } from "${fontTypeImportPath}"

// Auto-generated, manual changes will be lost, generated by optimizeAssets from @adaptive-ds/assets-optimizer
export const fontList = ${JSON.stringify(fontMap, null, 2)} as const satisfies Record<string, FontType>
`
}