import { imageSize } from "image-size"
import fs from "node:fs/promises"
import path from "node:path"
import { getOwnPackageName } from "../shared/getOwnPackageName.js"
import { isMissingDirError } from "../shared/isMissingDirError.js"
import { walkFiles } from "../shared/walkFiles.js"
import { createVideoPreviewPath } from "../video/createVideoPreviewPath.js"
import { supportedVideoSourceExtensions } from "../video/supportedVideoSourceExtensions.js"
import type { ImageType, VideoType } from "./AssetListTypes.js"
import { formatGeneratedCodeFile } from "./formatGeneratedCodeFile.js"
import { getAssetKey } from "./getAssetKey.js"
import { loadExistingAssetList } from "./loadExistingAssetList.js"
import { sortAssetMap } from "./sortAssetMap.js"

export async function generateVideoList(
  videosDirectory: string,
  outputPath: string,
  videoTypeImportPath?: string,
): Promise<void> {
  const resolvedVideoTypeImportPath = videoTypeImportPath ?? (await getOwnPackageName(import.meta.url))
  const existingVideos = await loadExistingAssetList<VideoType>(outputPath, "videoList")
  const videoMap = sortAssetMap(await processVideoFiles(videosDirectory, existingVideos))

  await fs.mkdir(path.dirname(outputPath), { recursive: true })
  await Bun.write(outputPath, createGeneratedVideoListContent(videoMap, resolvedVideoTypeImportPath))
  await formatGeneratedCodeFile(outputPath)
  console.log(`Generated ${Object.keys(videoMap).length} videos to ${outputPath}`)
}

async function processVideoFiles(
  directory: string,
  existingVideos: Record<string, VideoType>,
): Promise<Record<string, VideoType>> {
  const videoMap: Record<string, VideoType> = {}

  let filePaths: string[]
  try {
    filePaths = await walkFiles(directory)
  } catch (error) {
    if (isMissingDirError(error)) {
      return videoMap
    }

    throw error
  }

  for (const filePath of filePaths) {
    const extension = path.extname(filePath).toLowerCase()
    if (!supportedVideoSourceExtensions.has(extension)) {
      continue
    }

    const relativePath = path.relative(directory, filePath)
    const key = getAssetKey(filePath)
    const previewPath = createVideoPreviewPath(filePath)
    const previewBuffer = await fs.readFile(previewPath)
    const previewDimensions = imageSize(previewBuffer)
    if (!previewDimensions.width || !previewDimensions.height) {
      continue
    }

    const fileName = path.basename(filePath, extension)
    const existingPreview = existingVideos[key]?.image

    videoMap[key] = {
      path: relativePath,
      mimeType: getVideoMimeType(extension),
      image: {
        path: path.relative(directory, previewPath),
        width: previewDimensions.width,
        height: previewDimensions.height,
        alt: existingPreview?.alt || fileName.replace(/[-_]/g, " "),
        mimeType: "image/jpeg",
      } satisfies ImageType,
    }
  }
  return videoMap
}

function createGeneratedVideoListContent(videoMap: Record<string, VideoType>, videoTypeImportPath: string): string {
  return `import type { VideoType } from "${videoTypeImportPath}"

// Auto-generated, manual changes will be lost, generated by optimizeAssets from @adaptive-ds/assets-optimizer
export const videoList = ${JSON.stringify(videoMap, null, 2)} as const satisfies Record<string, VideoType>
`
}

function getVideoMimeType(extension: string): string {
  switch (extension) {
    case ".mp4":
    case ".m4v":
      return "video/mp4"
    case ".mov":
      return "video/quicktime"
    case ".webm":
      return "video/webm"
    case ".avi":
      return "video/x-msvideo"
    case ".mkv":
      return "video/x-matroska"
    default:
      return "application/octet-stream"
  }
}
